---
# tasks file for package-mgmt
- name: Add Docker repo key
  ansible.builtin.shell: curl -fsSL {{ docker_repo_key }} | gpg --dearmor --batch --yes -o /etc/apt/trusted.gpg.d/docker-ce-keyring.gpg

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    
- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  community.general.pipx:
    name: docker

- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add Sublime Text repo key
  ansible.builtin.shell: curl -fsSL {{ sublime_repo_key }} | gpg --dearmor --batch --yes -o /etc/apt/trusted.gpg.d/sublime-text-keyring.gpg

- name: Add Sublime Text repo
  ansible.builtin.apt_repository:
    repo: "{{ sublime_repo }}"
    state: present

- name: Ensuring all packages are up to date
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Installing one-off packages from package manager
  ansible.builtin.package:
    name:
    - bloodhound
    - build-essential
    - bytecode-viewer
    - clang
    - cmake
    - crackmapexec
    - curl
    - default-jdk
    - default-jre
    - docker-ce
    - docker-compose
    - eog
    - feroxbuster
    - flex
    - forensics-extra
    - gawk
    - gdb
    - gdbserver
    - ghidra
    - git
    - gobuster
    - golang-go
    - jq
    - jxplorer
    - libffi-dev
    - liblzma-dev
    - libssl-dev
    - libxml2-dev
    - ltrace
    - ncat
    - neo4j
    - ntpdate
    - mingw-w64
    - patch
    - powershell
    - python3
    - python3-dev
    - python3-pip
    - p7zip-full
    - remmina
    - rlwrap
    - samba
    - seclists
    - steghide
    - strace
    - sublime-text
    - terminator
    - tmux
    - xclip
    - xfce4-terminal
    - zaproxy
    - zlib1g-dev
    state: latest
